resourcePackages:
  - io.baris.petclinic.dropwizard
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '1.0'
    title: Pet Clinic with Dropwizard
    description: Pet Clinic with Dropwizard
    termsOfService: https://baris.io/terms/
    contact:
      email: basaran.baris@gmail.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
